CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_subject VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    nickname VARCHAR(50),
    onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE preference_vocabulary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    domain VARCHAR(50) NOT NULL,
    parent_code VARCHAR(100) REFERENCES preference_vocabulary(code),
    display_name VARCHAR(100) NOT NULL
);

CREATE TABLE user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    vocabulary_code VARCHAR(100) NOT NULL REFERENCES preference_vocabulary(code),
    raw_value VARCHAR(255) NOT NULL,
    sentiment VARCHAR(20) NOT NULL,
    strength VARCHAR(20) NOT NULL,
    mapping_type VARCHAR(20) NOT NULL,
    source_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_user_preferences_user_vocabulary UNIQUE (user_id, vocabulary_code)
);

CREATE INDEX idx_user_preferences_user_id ON user_preferences (user_id);

CREATE TABLE meeting_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    invite_code VARCHAR(8) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES meeting_groups(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id)
);

CREATE UNIQUE INDEX uk_group_members_single_host
    ON group_members (group_id)
    WHERE role = 'HOST' AND status <> 'DECLINED';

CREATE INDEX idx_group_members_user_id ON group_members (user_id);

CREATE TABLE meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES meeting_groups(id),
    created_by BIGINT NOT NULL REFERENCES users(id),
    purpose VARCHAR(1000),
    region VARCHAR(100),
    schedule_search_from DATE,
    schedule_search_to DATE,
    preferred_time_of_day VARCHAR(30),
    preference_survey_deadline DATE,
    status VARCHAR(30) NOT NULL,
    confirmed_start_at TIMESTAMPTZ,
    confirmed_end_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_meetings_group_id ON meetings (group_id);
CREATE INDEX idx_meetings_upcoming
    ON meetings (group_id, confirmed_start_at)
    WHERE status = 'CONFIRMED';

CREATE TABLE meeting_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    group_member_id BIGINT NOT NULL REFERENCES group_members(id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_meeting_participants_meeting_member UNIQUE (meeting_id, group_member_id)
);

CREATE INDEX idx_meeting_participants_member_id ON meeting_participants (group_member_id);

CREATE TABLE meeting_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_meeting_chat_messages_meeting
    ON meeting_chat_messages (meeting_id, id);

CREATE TABLE meeting_memories (
    meeting_id BIGINT PRIMARY KEY REFERENCES meetings(id) ON DELETE CASCADE,
    memory JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
