ALTER TABLE meeting_participants
    ADD COLUMN availability_submitted_at TIMESTAMPTZ;

CREATE TABLE meeting_available_dates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_participant_id BIGINT NOT NULL REFERENCES meeting_participants(id) ON DELETE CASCADE,
    available_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_meeting_available_dates_participant_date
        UNIQUE (meeting_participant_id, available_date)
);

CREATE INDEX idx_meeting_available_dates_participant
    ON meeting_available_dates (meeting_participant_id, available_date);
