CREATE TABLE group_memories (
    group_id BIGINT PRIMARY KEY REFERENCES meeting_groups(id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE meeting_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    generation INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    external_place_id VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    place_provider VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    external_url TEXT,
    proposed_start_at TIMESTAMPTZ NOT NULL,
    proposed_end_at TIMESTAMPTZ NOT NULL,
    reasons JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_meeting_suggestions_generation_rank UNIQUE (meeting_id, generation, rank),
    CONSTRAINT uk_meeting_suggestions_generation_place UNIQUE (meeting_id, generation, external_place_id)
);

CREATE INDEX idx_meeting_suggestions_meeting_generation ON meeting_suggestions (meeting_id, generation DESC);

ALTER TABLE meetings ADD COLUMN confirmed_suggestion_id BIGINT REFERENCES meeting_suggestions(id);
