CREATE TABLE meeting_calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    google_event_id VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_meeting_calendar_events_meeting_user UNIQUE (meeting_id, user_id)
);

CREATE INDEX idx_meeting_calendar_events_meeting_id ON meeting_calendar_events(meeting_id);
