-- Base vocabulary must be inserted before children because parent_code is a self-referencing FK.
INSERT INTO preference_vocabulary (code, domain, display_name, parent_code) VALUES
('MEAT', 'FOOD', '육류', NULL),
('BEEF', 'FOOD', '소고기', 'MEAT'),
('PORK', 'FOOD', '돼지고기', 'MEAT'),
('CHICKEN', 'FOOD', '닭고기', 'MEAT'),
('LAMB', 'FOOD', '양고기', 'MEAT'),
('DUCK', 'FOOD', '오리고기', 'MEAT'),
('SEAFOOD', 'FOOD', '해산물', NULL),
('RAW_FISH', 'FOOD', '회', 'SEAFOOD'),
('FLOUNDER', 'FOOD', '광어', 'RAW_FISH'),
('SALMON', 'FOOD', '연어', 'RAW_FISH'),
('TUNA', 'FOOD', '참치', 'RAW_FISH'),
('SHELLFISH', 'FOOD', '조개류', 'SEAFOOD'),
('CRAB', 'FOOD', '게', 'SEAFOOD'),
('SHRIMP', 'FOOD', '새우', 'SEAFOOD'),
('VEGETABLE', 'FOOD', '채소 위주 음식', NULL),
('NOODLE', 'FOOD', '면 요리', NULL),
('SPICY_FOOD', 'FOOD', '매운 음식', NULL),
('GREASY_FOOD', 'FOOD', '기름진 음식', NULL),
('LIGHT_FOOD', 'FOOD', '담백한 음식', NULL),
('ACTIVE', 'ACTIVITY', '활동적인 모임', NULL),
('BOARD_GAME', 'ACTIVITY', '보드게임', NULL),
('BOWLING', 'ACTIVITY', '볼링', NULL),
('ESCAPE_ROOM', 'ACTIVITY', '방탈출', NULL),
('KARAOKE', 'ACTIVITY', '노래방', NULL),
('WALKING', 'ACTIVITY', '산책/걷기', NULL),
('SPORTS_WATCHING', 'ACTIVITY', '스포츠 관람', NULL),
('PC_ROOM', 'ACTIVITY', 'PC방', NULL),
('QUIET', 'MOOD', '조용한 분위기', NULL),
('LIVELY', 'MOOD', '시끌벅적한 분위기', NULL),
('COZY', 'MOOD', '아늑한 분위기', NULL),
('TRENDY', 'MOOD', '힙하고 트렌디한 분위기', NULL),
('ALCOHOL', 'DRINK', '음주', NULL),
('COFFEE', 'DRINK', '커피/카페인', NULL)
ON CONFLICT (code) DO NOTHING;

INSERT INTO preference_vocabulary (code, domain, display_name, parent_code) VALUES
('KOREAN_FOOD', 'FOOD', '한식', NULL),
('JAPANESE_FOOD', 'FOOD', '일식', NULL),
('CHINESE_FOOD', 'FOOD', '중식', NULL),
('WESTERN_FOOD', 'FOOD', '양식', NULL),
('ASIAN_FOOD', 'FOOD', '아시안/동남아 음식', NULL),
('EEL', 'FOOD', '장어', 'SEAFOOD'),
('OCTOPUS', 'FOOD', '문어', 'SEAFOOD'),
('SQUID', 'FOOD', '오징어', 'SEAFOOD'),
('MACKEREL', 'FOOD', '고등어', 'SEAFOOD'),
('EGG', 'FOOD', '계란/알류', NULL),
('MILK', 'FOOD', '우유', NULL),
('WHEAT', 'FOOD', '밀', NULL),
('PEANUT', 'FOOD', '땅콩', NULL),
('BUCKWHEAT', 'FOOD', '메밀', NULL),
('DESSERT', 'FOOD', '디저트', NULL),
('BAKERY', 'FOOD', '베이커리/빵', NULL),
('MOVIE', 'ACTIVITY', '영화 관람', NULL),
('CAFE_HANGOUT', 'ACTIVITY', '카페에서 노는 것', NULL),
('BILLIARDS', 'ACTIVITY', '당구', NULL),
('DARTS', 'ACTIVITY', '다트', NULL),
('HIKING', 'ACTIVITY', '등산', NULL),
('PICNIC', 'ACTIVITY', '피크닉', NULL),
('EXHIBITION', 'ACTIVITY', '전시/공연 관람', NULL),
('DRIVE', 'ACTIVITY', '드라이브', NULL),
('SHOPPING', 'ACTIVITY', '쇼핑', NULL),
('OUTDOOR', 'MOOD', '야외/테라스 자리', NULL),
('CASUAL', 'MOOD', '편안하고 캐주얼한 분위기', NULL),
('BEER', 'DRINK', '맥주', 'ALCOHOL'),
('SOJU', 'DRINK', '소주', 'ALCOHOL'),
('WINE', 'DRINK', '와인', 'ALCOHOL'),
('COCKTAIL', 'DRINK', '칵테일', 'ALCOHOL'),
('TEA', 'DRINK', '차', NULL)
ON CONFLICT (code) DO NOTHING;
